---
- name: Ensure Docker SDK for Python is installed
  hosts: servers
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install pip for Python 3
      apt:
        name: python3-pip
        state: present
      when: ansible_os_family == "Debian"
    - name: Install Docker SDK for Python
      pip:
        name: docker
        state: present
        executable: pip3
      become: yes